#!/usr/bin/env bash
set -euo pipefail

# Fixture tests for classify_audit_verdict (scripts/lib/audit-verdict.sh).
# Hermetic: writes fixtures under a temp directory, no network, no agent calls.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
. "$ROOT/scripts/lib/audit-verdict.sh"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

FAILED=0
COUNT=0

# name, expected class, file contents (printf format string)
check() {
    local name="$1" expected="$2" contents="$3"
    local file="$TMP/fixture"
    COUNT=$((COUNT + 1))
    printf "$contents" > "$file"
    local actual
    actual="$(classify_audit_verdict "$file")"
    if [[ "$actual" != "$expected" ]]; then
        echo "FAIL: $name — expected $expected, got $actual"
        FAILED=$((FAILED + 1))
    fi
}

check 'labelled-not-ready' NOT_READY 'Conclusion: NOT READY\n'
check 'labelled-ready' READY 'Conclusion: READY\n'
check 'labelled-ambiguous' UNKNOWN 'Conclusion: READY or NOT READY\n'

check_missing() {
    local name="$1" expected="$2" file="$3"
    COUNT=$((COUNT + 1))
    local actual
    actual="$(classify_audit_verdict "$file")"
    if [[ "$actual" != "$expected" ]]; then
        echo "FAIL: $name — expected $expected, got $actual"
        FAILED=$((FAILED + 1))
    fi
}

# --- the three documented verdicts -----------------------------------------
check "bare READY"                READY                            'READY\n'
check "bare READY WITH"           READY_WITH_NON_BLOCKING_ISSUES   'READY WITH NON-BLOCKING ISSUES\n'
check "bare NOT READY"            NOT_READY                        'NOT READY\n'
check "verdict after a report"    READY                            '# Final audit\n\nAll checks pass.\n\nREADY\n'
check "NOT READY after a report"  NOT_READY                        '# Final audit\n\nBlocking finding.\n\nNOT READY\n'

# --- AR-005: exact-match, last-non-blank-line rules ------------------------
check "NOT READY finding, READY last" READY   'Finding: NOT READY without a fix.\n\nREADY\n'
check "phrase inside prose"        UNKNOWN    'Rerun until READY\n'
check "markdown heading"           READY      '## READY\n'
check "bold emphasis"              READY      '**READY**\n'
check "underscore emphasis"        NOT_READY  '_NOT READY_\n'
check "two phrases concatenated"   UNKNOWN    'READY NOT READY\n'
check "verdict plus trailing text" UNKNOWN    'NOT READY - see findings above\n'
check "trailing blank lines"       READY      'READY\n\n\n'
check "trailing whitespace lines"  READY      'READY\n   \n\t\n'
check "CRLF line endings"          READY      'READY\r\n'
check "CRLF with report"           NOT_READY  'Audit\r\n\r\nNOT READY\r\n'
check "footer after the verdict"   UNKNOWN    'READY\n\nGenerated by the reviewer CLI.\n'
check "lowercase"                  UNKNOWN    'ready\n'
check "mixed case"                 UNKNOWN    'Ready\n'
check "leading indentation"        READY      '    READY\n'
check "no trailing newline"        READY      'READY'
check "empty file"                 UNKNOWN    ''
check "blank lines only"           UNKNOWN    '\n\n   \n'
check "unrelated prose"            UNKNOWN    'The audit did not reach a conclusion.\n'

check_missing "absent file"        UNKNOWN    "$TMP/does-not-exist"
check_missing "empty argument"     UNKNOWN    ""

if [[ "$FAILED" -ne 0 ]]; then
    echo "audit-verdict-test.sh: $FAILED of $COUNT checks failed"
    exit 1
fi

echo "audit-verdict-test.sh: $COUNT checks passed"
