#!/usr/bin/env python3
"""Driver-sealed PR attestation.

Every value is read from driver-controlled workflow state (the PR journal,
`origin`, `approvals/`, `audit-verdict`, `green-check.tsv`, `session-totals.json`,
`VERSION`). No agent-authored file is ever a source, and no value is inferred:
evidence that is missing, unreadable or not of the expected shape is sealed as
`unavailable`. The one exception fails closed: without the audited tree there
is nothing to attest, so sealing raises.
"""
import hashlib
import json
from pathlib import Path
import re

MARKER = 'UNCLE CHANGE ATTESTATION'
UNAVAILABLE = 'unavailable'
STATE = Path('.uncle/workflow')

# Fixed rows, fixed order, fixed labels. A key absent from the sealed dict is
# not rendered; a key present but unreadable renders `unavailable`.
FIELDS = (
    ('issue', 'Issue'),
    ('specification', 'Specification (SHA-256)'),
    ('implementation', 'Implementation agent'),
    ('review_agent', 'Review agent'),
    ('review_result', 'Review result'),
    ('finding_acceptance', 'Finding acceptance'),
    ('verification', 'Verification'),
    ('tree', 'Audited tree'),
    ('published_commit', 'Published commit'),
    ('gate_plan', 'Gate: plan approval'),
    ('gate_publication', 'Gate: publication'),
    ('audit_override', 'Audit override'),
    ('version', 'Uncle version'),
)
KEYS = tuple(key for key, _ in FIELDS)
# Rows that only exist when the state that produces them exists.
OPTIONAL = ('finding_acceptance', 'published_commit', 'audit_override')

VERDICTS = ('READY', 'READY_WITH_NON_BLOCKING_ISSUES', 'NOT_READY', 'UNKNOWN')
PASSED = ('PASS', 'FIXED')
# A PR body is public. Anything shaped like a credential is not a field value,
# whatever state file it came out of.
SECRET = re.compile(r'ghp_|gho_|ghu_|ghs_|ghr_|github_pat_|sk-|xox[abprs]|AIza', re.I)
HASH = r'[0-9a-f]{7,64}'
HEADER = ('Generated by Uncle from driver-held workflow state. Fields whose '
          'evidence\nwas missing read `unavailable`; nothing here is inferred.')


class AttestationError(ValueError):
    """Authoritative state is unusable; no PR may be created."""


def _read(path):
    try:
        return Path(path).read_text(encoding='utf-8', errors='replace')
    except OSError:
        return ''


def _digest(path):
    try:
        return hashlib.sha256(Path(path).read_bytes()).hexdigest()
    except OSError:
        return ''


def atom(value, pattern):
    """A single public token, or None. Bounded, one line, never credential-shaped."""
    value = '' if value is None else str(value)
    if len(value) > 80 or SECRET.search(value) or re.search(r'[\x00-\x1f\x7f]', value):
        return None
    return value if re.fullmatch(pattern, value) else None


def _identity(runner, model):
    # A runner is configured as a name or as a path to an agent script; only the
    # public name goes in the body, and only if it still looks like a name.
    runner = str(runner or '').replace('\\', '/').rsplit('/', 1)[-1]
    runner = re.sub(r'^(?:agent|reviewer)-', '', runner)
    runner = re.sub(r'\.(?:sh|cmd|bat|ps1|exe)$', '', runner)
    runner = atom(runner.lower(), r'[a-z][a-z0-9._+-]{0,40}')
    if not runner:
        return None
    model = atom(model or '', r'[A-Za-z0-9._:+/-]{1,80}')
    return runner + (' (' + model + ')' if model else '')


def _issue(origin):
    row = str(origin or '').strip().split('\t')
    if len(row) != 3 or row[2] != 'gh' or not row[1].isdigit():
        return None
    return atom('#' + row[1], r'#[0-9]+')


def _approved(state, root, name):
    """The approved digest, only while the artifact still hashes to it."""
    recorded = atom(_read(Path(state) / 'approvals' / (name + '.sha256')).strip(), HASH)
    if not recorded or recorded != _digest(Path(root) / (name + '.md')):
        return None
    return recorded


def _gate_label(value):
    if value == 'unattended':
        return 'APPROVED (unattended)'
    # A supervisor-relayed answer is machine-made at a human's request; the
    # receipt keeps the request. It is labelled as such, never as human.
    match = re.fullmatch(r'supervisor:(explicit|standing):(.*)', value or '', re.S)
    if match:
        return 'APPROVED (supervisor:%s%s)' % (match.group(1), ':' + match.group(2).strip() if match.group(2).strip() else '')
    match = re.fullmatch(r'disabled:(.*)', value or '', re.S)
    if match:
        return 'SKIPPED (' + match.group(1).strip() + ')'
    return 'APPROVED (human)'


def _gate_plan(state, root):
    if not _approved(state, root, 'CHANGE_PLAN'):
        return None
    by = Path(state) / 'approvals' / 'CHANGE_PLAN.approved-by'
    if not by.exists():
        return None
    # The delegation record, when the driver wrote one; older runs kept the
    # `unattended`/`supervisor:*` value in `.approved-by` itself.
    delegated = _read(Path(state) / 'approvals' / 'CHANGE_PLAN.delegated-by').strip()
    return _gate_label(delegated or _read(by).strip())


def from_statement(statement):
    """The PR block rows, read from a Statement's predicate. The rendering
    vocabulary (tree, agent, PR) appears only here."""
    predicate = statement.get('predicate') if isinstance(statement, dict) else None
    predicate = predicate if isinstance(predicate, dict) else {}
    envelopes = predicate.get('envelopes') if isinstance(predicate.get('envelopes'), dict) else {}
    approvals = {row.get('gate'): row for row in predicate.get('approvals') or [] if isinstance(row, dict)}

    def gate(name):
        row = approvals.get(name)
        if not row:
            return None
        return _gate_label(row.get('delegated_by') or ('' if row.get('approved_by') else 'unattended'))

    def producer(stage):
        row = (envelopes.get(stage) or {}).get('producer') or {}
        return _identity(row.get('runner'), None if row.get('model') in ('driver', 'unavailable') else row.get('model'))

    audit = envelopes.get('audit') or {}
    verdict = audit.get('reason') if audit.get('reason') in VERDICTS else None
    if not verdict and audit.get('result'):
        verdict = {'pass': 'READY', 'fail': 'NOT_READY'}.get(audit['result'], UNAVAILABLE)
    verification = envelopes.get('verification') or {}
    source = predicate.get('source') if isinstance(predicate.get('source'), dict) else {}
    subjects = statement.get('subject') if isinstance(statement, dict) else None
    subject = subjects[0] if isinstance(subjects, list) and subjects and isinstance(subjects[0], dict) else {}
    tree = atom(str((subject.get('digest') or {}).get('gitTree') or ''), HASH)
    sealed = {
        'issue': atom('#' + str(source.get('issue') or ''), r'#[0-9]+'),
        'specification': atom((approvals.get('CHANGE_SPEC') or {}).get('digest') or '', HASH),
        'implementation': producer('implementation'),
        'review_agent': producer('audit'),
        'review_result': verdict,
        'verification': atom(verification.get('reason') or verification.get('result') or '', r'[ -~]{1,80}'),
        'tree': tree[:12] if tree else None,
        'gate_plan': gate('CHANGE_PLAN'),
        'gate_publication': gate('publication'),
        'version': atom(str(predicate.get('uncle_version') or ''), r'[0-9A-Za-z._+-]{1,40}'),
    }
    sealed = {key: value or UNAVAILABLE for key, value in sealed.items()}
    override = (envelopes.get('release') or {}).get('override')
    if isinstance(override, dict) and override.get('gate'):
        sealed['audit_override'] = 'operator override (' + str(override['gate']) + ') recorded; no release'
    return sealed


def _records(state):
    try:
        saved = json.loads((Path(state) / 'session-totals.json').read_text(encoding='utf-8'))
    except (OSError, ValueError):
        return []
    rows = saved.get('records') if isinstance(saved, dict) else None
    return [r for r in rows if isinstance(r, dict)] if isinstance(rows, list) else []


def _agent(state, kind, stage):
    rows = [r for r in _records(state)
            if r.get('kind') == kind and not r.get('speculative')
            and r.get('process_exit') == 0 and not r.get('reported_error')
            and isinstance(r.get('stage'), str) and stage(r['stage'])]
    if not rows:
        return None
    row = max(enumerate(rows), key=lambda pair: (pair[1].get('ended_at') or 0, pair[0]))[1]
    return _identity(row.get('runner'), row.get('model'))


def _implementation_stage(stage):
    return stage == 'implementation' or bool(re.fullmatch(r'implementation-step-[0-9]+', stage))


def _verdict_row(path):
    row = _read(path).strip().split('\t')
    return row if len(row) == 3 and row[1] in VERDICTS else None


def _verdicts(state, journal):
    # Only rows bound to this journal's audit count; a stale `.original` from
    # an earlier run names a different FINAL_AUDIT.md.
    rows = [_verdict_row(Path(state) / name) for name in ('audit-verdict.original', 'audit-verdict')]
    return [r if r and r[2] == journal.get('audit_hash') else None for r in rows]


def _review_result(state, journal):
    # The auditor's own verdict outranks the verdict the driver rewrote after
    # the operator decided each finding: acceptance is a separate row.
    original, current = _verdicts(state, journal)
    row = original or current
    return row[1] if row else None


def _acceptance(state, journal):
    original, current = _verdicts(state, journal)
    if original and current and original[1] == 'NOT_READY' and current[1].startswith('READY'):
        return 'operator accepted each auditor finding'
    return None


def _verification(state):
    counts = {'pass': 0, 'pre': 0, 'regressed': 0}
    total = 0
    for line in _read(Path(state) / 'green-check.tsv').splitlines():
        label = line.split('\t')[0].strip()
        if not label:
            continue
        total += 1
        if label in PASSED:
            counts['pass'] += 1
        elif label == 'PREEXISTING':
            counts['pre'] += 1
        elif label == 'REGRESSION':
            counts['regressed'] += 1
    if not total:
        return None
    value = '%d commands: %d pass, %d pre-existing, %d regressed' % (
        total, counts['pass'], counts['pre'], counts['regressed'])
    return atom(value, r'[0-9]+ commands: [0-9]+ pass, [0-9]+ pre-existing, [0-9]+ regressed')


def _override(state, journal):
    if (Path(state) / 'audit-override').exists():
        return 'operator override of the audit gate'
    record = _read(Path(state) / 'pr' / 'verdict-override').strip().split('\t')
    if (len(record) == 4 and record[0] == journal.get('verdict_run')
            and record[2] == journal.get('audit_hash') and record[1] in VERDICTS):
        return 'operator override over ' + record[1]
    return None


def _version(version, lib):
    version = str(version or '').strip()
    if not version and lib:
        version = _read(Path(lib).resolve().parents[1] / 'VERSION').strip()
    return atom(version, r'[0-9A-Za-z._+-]{1,40}')


def seal(journal, state=STATE, root='.', version='', lib=None):
    """Freeze the attestation from state. Values are never read again at render."""
    tree = atom(str(journal.get('commit_tree') or ''), HASH)
    if not tree:
        raise AttestationError('the audited tree is missing from the PR journal')
    sealed = {
        'issue': _issue(journal.get('origin')),
        'specification': _approved(state, root, 'CHANGE_SPEC'),
        'implementation': _agent(state, 'agent', _implementation_stage),
        'review_agent': _agent(state, 'reviewer', lambda s: s == 'final-audit'),
        'review_result': _review_result(state, journal),
        'verification': _verification(state),
        'tree': tree[:12],
        'gate_plan': _gate_plan(state, root),
        'gate_publication': None,
        'version': _version(version, lib),
    }
    sealed = {key: value or UNAVAILABLE for key, value in sealed.items()}
    sealed.update(_post_bind(journal, state))
    return sealed


def _post_bind(journal, state):
    """Rows the driver itself writes after bind (finding decisions, overrides, the commit)."""
    rows = {}
    acceptance = _acceptance(state, journal)
    if acceptance:
        rows['finding_acceptance'] = acceptance
    head = atom(str(journal.get('intended_head') or ''), HASH)
    if head:
        rows['published_commit'] = head[:12]
    override = _override(state, journal)
    if override:
        rows['audit_override'] = override
    return rows


def amend(sealed, journal, state=STATE):
    """The bind seal plus driver-written post-bind rows. Sealed values are never rewritten."""
    merged = {key: value for key, value in dict(sealed).items() if key in KEYS}
    for key, value in _post_bind(journal, state).items():
        merged.setdefault(key, value)
    return merged


def render(sealed):
    """The block exactly as it appears in the PR body. Pure; re-validates values."""
    sealed = sealed if isinstance(sealed, dict) else {}
    rows = [(label, sealed.get(key)) for key, label in FIELDS
            if key in sealed or key not in OPTIONAL]
    width = max(len(label) for label, _ in rows)
    lines = [MARKER, '', HEADER, '']
    for label, value in rows:
        if not isinstance(value, str) or not atom(value, r'[ -~]{1,80}'):
            value = UNAVAILABLE
        lines.append(label.ljust(width) + '  ' + value)
    return '```text\n' + '\n'.join(lines) + '\n```\n'


def attach_body(body, sealed):
    """Insert the block after the operator's sections and before any `Closes` trailer."""
    body = body or ''
    if MARKER in body:
        return body
    lines = body.rstrip('\n').split('\n')
    trailer = []
    while lines and (not lines[-1].strip() or lines[-1].startswith('Closes ')):
        trailer.insert(0, lines.pop())
    text = '\n'.join(lines).rstrip('\n')
    text = (text + '\n\n' if text else '') + render(sealed)
    trailer = [line for line in trailer if line.strip()]
    if trailer:
        text += '\n' + '\n'.join(trailer) + '\n'
    return text
